# Generated by Django 5.2.12 on 2026-03-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio_en", models.TextField()),
                ("bio_ru", models.TextField(blank=True)),
                ("bio_lv", models.TextField(blank=True)),
                ("education_en", models.TextField(blank=True)),
                ("education_ru", models.TextField(blank=True)),
                ("education_lv", models.TextField(blank=True)),
                ("qualifications_en", models.TextField(blank=True)),
                ("qualifications_ru", models.TextField(blank=True)),
                ("qualifications_lv", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="about/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "About",
                "db_table": "pages_about",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(max_length=255)),
                ("title_ru", models.CharField(blank=True, max_length=255)),
                ("title_lv", models.CharField(blank=True, max_length=255)),
                ("description_en", models.TextField()),
                ("description_ru", models.TextField(blank=True)),
                ("description_lv", models.TextField(blank=True)),
                ("year", models.IntegerField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="book/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Book",
                "db_table": "pages_book",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("linkedin_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contact",
                "db_table": "pages_contact",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(max_length=255)),
                ("title_ru", models.CharField(blank=True, max_length=255)),
                ("title_lv", models.CharField(blank=True, max_length=255)),
                ("company_en", models.CharField(max_length=255)),
                ("company_ru", models.CharField(blank=True, max_length=255)),
                ("company_lv", models.CharField(blank=True, max_length=255)),
                ("description_en", models.TextField(blank=True)),
                ("description_ru", models.TextField(blank=True)),
                ("description_lv", models.TextField(blank=True)),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experience",
                "db_table": "pages_experience",
                "ordering": ["-order", "-start_year"],
            },
        ),
    ]
