# flake8: noqa: E501
from django.db import migrations


TEXT_BLOCKS = [
    ("solutions", "hero", "heroEyebrow", "Solutions", "Решения", "Risinājumi"),
    ("solutions", "hero", "title", "Solutions", "Решения", "Risinājumi"),
    (
        "solutions",
        "hero",
        "lead",
        "Generalized solution patterns for recurring welding problems: problem class, likely cause, engineering analysis, method, and expected direction of improvement.",
        "Обобщённые паттерны решений для повторяющихся сварочных задач: класс проблемы, вероятная причина, инженерный анализ, метод и ожидаемое направление улучшения.",
        "Vispārināti risinājumu modeļi atkārtotām metināšanas problēmām: problēmas klase, iespējamais cēlonis, inženiertehniskā analīze, metode un sagaidāmais uzlabojuma virziens.",
    ),
    (
        "solutions",
        "validation",
        "validationEyebrow",
        "Validation layer",
        "Слой подтверждения",
        "Pierādījuma slānis",
    ),
    (
        "solutions",
        "validation",
        "validationTitle",
        "Real cases live in Experience",
        "Реальные кейсы находятся в разделе «Опыт»",
        "Reālie piemēri atrodas sadaļā Pieredze",
    ),
    (
        "solutions",
        "validation",
        "validationText",
        "Solutions describe reusable patterns. Experience shows where similar logic was applied in real production contexts with roles, periods, actions, and observed outcomes.",
        "Решения описывают повторяемые паттерны. Опыт показывает, где похожая логика применялась в реальном производственном контексте: роли, периоды, действия и наблюдаемый эффект.",
        "Risinājumi apraksta atkārtojamus modeļus. Pieredze rāda, kur līdzīga loģika izmantota reālā ražošanas kontekstā: lomas, periodi, darbības un novērotais efekts.",
    ),
    (
        "solutions",
        "validation",
        "validationCta",
        "See real-world validation",
        "Посмотреть подтверждение на практике",
        "Skatīt praktisko pierādījumu",
    ),
    (
        "solutions",
        "nav",
        "navAriaLabel",
        "Solutions navigation",
        "Навигация по решениям",
        "Risinājumu navigācija",
    ),
    (
        "solutions",
        "nav",
        "navTitle",
        "Choose a production task",
        "Выберите производственную задачу",
        "Izvēlieties ražošanas uzdevumu",
    ),
    (
        "solutions",
        "nav",
        "navReadMore",
        "Go to section",
        "Перейти к разделу",
        "Pāriet uz sadaļu",
    ),
    ("solutions", "labels", "problem", "Problem", "Проблема", "Problēma"),
    ("solutions", "labels", "cause", "Cause", "Причина", "Cēlonis"),
    (
        "solutions",
        "labels",
        "engineeringAnalysis",
        "Engineering analysis",
        "Инженерный анализ",
        "Inženiertehniskā analīze",
    ),
    ("solutions", "labels", "solution", "Solution", "Решение", "Risinājums"),
    (
        "solutions",
        "labels",
        "expectedResult",
        "Expected direction",
        "Направление улучшения",
        "Uzlabojuma virziens",
    ),
    (
        "solutions",
        "final_cta",
        "finalCtaTitle",
        "Ready to define the next step?",
        "Готовы определить следующий шаг?",
        "Gatavi noteikt nākamo soli?",
    ),
    (
        "solutions",
        "final_cta",
        "finalCtaText",
        "Describe the task, defect pattern, material, process, and constraints.",
        "Опишите задачу, дефект, материал, процесс и ограничения.",
        "Aprakstiet uzdevumu, defektu, materiālu, procesu un ierobežojumus.",
    ),
    ("solutions", "final_cta", "finalCtaContact", "Contact", "Контакт", "Kontakts"),
    (
        "solutions",
        "nav_defectReduction",
        "title",
        "Defect reduction",
        "Снижение дефектов",
        "Defektu samazināšana",
    ),
    (
        "solutions",
        "nav_defectReduction",
        "description",
        "Root-cause analysis of welding defects and process instability.",
        "Анализ причин появления дефектов сварки и нестабильности процесса.",
        "Metināšanas defektu un procesa nestabilitātes cēloņu analīze.",
    ),
    (
        "solutions",
        "nav_processOptimization",
        "title",
        "Process stability",
        "Стабильность процесса",
        "Procesa stabilitāte",
    ),
    (
        "solutions",
        "nav_processOptimization",
        "description",
        "Analysis and adjustment of welding parameters and production modes.",
        "Анализ и настройка сварочных параметров и производственных режимов.",
        "Metināšanas parametru un ražošanas režīmu analīze un regulēšana.",
    ),
    (
        "solutions",
        "nav_gasSelection",
        "title",
        "Shielding gas selection",
        "Подбор защитных газов",
        "Aizsarggāzu izvēle",
    ),
    (
        "solutions",
        "nav_gasSelection",
        "description",
        "Gas mix selection matched to material, process, and quality requirements.",
        "Подбор газовых смесей под материал, процесс и требования к качеству.",
        "Gāzu maisījumu izvēle pēc materiāla, procesa un kvalitātes prasībām.",
    ),
    (
        "solutions",
        "nav_training",
        "title",
        "Personnel training",
        "Обучение персонала",
        "Personāla apmācība",
    ),
    (
        "solutions",
        "nav_training",
        "description",
        "Training for welders and production personnel.",
        "Подготовка сварщиков и производственного персонала.",
        "Metinātāju un ražošanas personāla sagatavošana.",
    ),
    (
        "solutions",
        "nav_wpsSupport",
        "title",
        "Project support / WPS",
        "Поддержка проектов / WPS",
        "Projektu atbalsts / WPS",
    ),
    (
        "solutions",
        "nav_wpsSupport",
        "description",
        "Engineering support for implementing welding processes and WPS.",
        "Инженерное сопровождение внедрения сварочных процессов и WPS.",
        "Inženiertehnisks atbalsts metināšanas procesu un WPS ieviešanai.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "title",
        "Welding defect reduction",
        "Снижение дефектов сварки",
        "Metināšanas defektu samazināšana",
    ),
    (
        "solutions",
        "section_defectReduction",
        "problems_1",
        "Porosity, lack of fusion, burn-through, undercut, or unstable weld shape.",
        "Поры, непровары, прожоги, подрезы или нестабильная форма шва.",
        "Poras, necaurmetinājumi, pārdegumi, iegriezumi vai nestabila šuves forma.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "problems_2",
        "Recurring rejects without a clear root cause.",
        "Повторяющийся брак без понятной причины.",
        "Atkārtots brāķis bez skaidra iemesla.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "problems_3",
        "Different results between shifts, welders, or batches.",
        "Разный результат между сменами, сварщиками или партиями.",
        "Atšķirīgs rezultāts starp maiņām, metinātājiem vai partijām.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "problems_4",
        "Rework increases lead time and production cost.",
        "Переделки увеличивают сроки и стоимость производства.",
        "Pārstrāde palielina termiņus un ražošanas izmaksas.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "causes_1",
        "Parameters, edge preparation, gas flow, or access to the joint are not aligned.",
        "Режимы, подготовка кромок, расход газа или доступ к шву не согласованы между собой.",
        "Režīmi, malu sagatavošana, gāzes plūsma vai piekļuve šuvei nav savstarpēji saskaņoti.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "causes_2",
        "Actual shop-floor practice differs from the process sheet or WPS.",
        "Фактическая практика отличается от технологической карты или WPS.",
        "Faktiskā prakse atšķiras no tehnoloģiskās kartes vai WPS.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "analysisItems_1",
        "Checking welding parameters, gas flow, wire stickout, and edge preparation.",
        "Проверка режимов сварки, расхода газа, вылета проволоки и подготовки кромок.",
        "Metināšanas režīmu, gāzes plūsmas, stieples izvirzījuma un malu sagatavošanas pārbaude.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "analysisItems_2",
        "Reviewing base material, filler wire, shielding gas, and weld pool protection conditions.",
        "Анализ материала, присадочной проволоки, защитного газа и условий защиты сварочной ванны.",
        "Materiāla, piedevu stieples, aizsarggāzes un metināšanas vannas aizsardzības apstākļu analīze.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "analysisItems_3",
        "Matching defect patterns to the real production environment.",
        "Сопоставление дефектов с реальными условиями работы на производстве.",
        "Defektu salīdzināšana ar reālajiem darba apstākļiem ražošanā.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "analysisItems_4",
        "Checking whether the work follows the process sheet or WPS, if one exists.",
        "Проверка соблюдения технологической карты или WPS, если она есть.",
        "Tehnoloģiskās kartes vai WPS ievērošanas pārbaude, ja tāda ir.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "solutionSteps_1",
        "Define likely defect causes and verify them on samples or a production batch.",
        "Зафиксировать вероятные причины дефектов и проверить их на образцах или серии.",
        "Noteikt iespējamos defektu cēloņus un pārbaudīt tos uz paraugiem vai sērijas.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "solutionSteps_2",
        "Adjust parameters, preparation, shielding, or process control points.",
        "Скорректировать параметры, подготовку, газовую защиту или контрольные точки процесса.",
        "Koriģēt parametrus, sagatavošanu, aizsardzību vai procesa kontroles punktus.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "expectedResults_1",
        "A clear defect cause or a shortlist of likely causes.",
        "Понятная причина дефектов или список вероятных причин.",
        "Skaidrs defektu cēlonis vai iespējamo cēloņu saraksts.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "expectedResults_2",
        "Practical corrections to parameters and process steps.",
        "Практические корректировки параметров и процесса.",
        "Praktiskas parametru un procesa korekcijas.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "expectedResults_3",
        "Fewer rejects and less rework.",
        "Снижение брака и повторных переделок.",
        "Mazāk brāķa un atkārtotas pārstrādes.",
    ),
    (
        "solutions",
        "section_defectReduction",
        "expectedResults_4",
        "More stable quality between shifts and operators.",
        "Более стабильное качество между сменами и операторами.",
        "Stabilāka kvalitāte starp maiņām un operatoriem.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "title",
        "Welding process stability",
        "Стабильность сварочного процесса",
        "Metināšanas procesa stabilitāte",
    ),
    (
        "solutions",
        "section_processOptimization",
        "problems_1",
        "The process is unstable and depends on a specific welder.",
        "Процесс работает нестабильно и зависит от конкретного сварщика.",
        "Process ir nestabils un atkarīgs no konkrēta metinātāja.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "problems_2",
        "Parameters are adjusted manually without a clear operating window.",
        "Режимы подбираются вручную без понятного окна параметров.",
        "Režīmi tiek piemeklēti manuāli bez skaidra parametru loga.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "problems_3",
        "Productivity is low or the workflow has unnecessary steps.",
        "Низкая производительность или лишние операции.",
        "Zema produktivitāte vai liekas operācijas.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "problems_4",
        "Quality is acceptable, but production cost is too high.",
        "Есть качество, но слишком высокая себестоимость.",
        "Kvalitāte ir pieņemama, bet pašizmaksa ir pārāk augsta.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "causes_1",
        "There is no fixed working window or common rules for making the weld.",
        "Нет зафиксированного рабочего окна параметров и единых правил выполнения шва.",
        "Nav fiksēta darba parametru loga un vienotu noteikumu šuves izpildei.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "causes_2",
        "Equipment, fixtures, preparation, and consumables are treated separately instead of as one system.",
        "Оборудование, оснастка, подготовка и расходники работают как отдельные элементы, а не как система.",
        "Iekārtas, palīgierīces, sagatavošana un patēriņa materiāli netiek skatīti kā viena sistēma.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "analysisItems_1",
        "Reviewing current welding parameters, operation sequence, and access to the joint.",
        "Оценка текущих параметров сварки, последовательности операций и доступности шва.",
        "Esošo metināšanas parametru, operāciju secības un piekļuves šuvei novērtēšana.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "analysisItems_2",
        "Checking equipment, fixtures, consumables, and workplace organization.",
        "Проверка оборудования, оснастки, расходных материалов и организации рабочего места.",
        "Iekārtu, palīgierīču, patēriņa materiālu un darba vietas organizācijas pārbaude.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "analysisItems_3",
        "Comparing the actual process with product and customer requirements.",
        "Сравнение фактического процесса с требованиями изделия и заказчика.",
        "Faktiskā procesa salīdzināšana ar izstrādājuma un klienta prasībām.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "analysisItems_4",
        "Finding bottlenecks: arc time, preparation, cleaning, rework, gas use, and wire consumption.",
        "Поиск узких мест: время дуги, подготовка, зачистка, переделки, расход газа и проволоки.",
        "Šauro vietu meklēšana: loka laiks, sagatavošana, tīrīšana, pārstrāde, gāzes un stieples patēriņš.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "solutionSteps_1",
        "Define the working parameter range and process constraints.",
        "Определить рабочий диапазон параметров и ограничения процесса.",
        "Noteikt darba parametru diapazonu un procesa ierobežojumus.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "solutionSteps_2",
        "Clarify operation sequence, control points, and practical instructions for production.",
        "Уточнить последовательность операций, контрольные точки и понятные инструкции для производства.",
        "Precizēt operāciju secību, kontroles punktus un praktiskas instrukcijas ražošanai.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "expectedResults_1",
        "A more stable welding parameter window.",
        "Более устойчивое окно сварочных параметров.",
        "Stabilāks metināšanas parametru logs.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "expectedResults_2",
        "Less dependence on individual operator habits.",
        "Меньше зависимости от индивидуальных привычек оператора.",
        "Mazāka atkarība no operatora individuālajiem ieradumiem.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "expectedResults_3",
        "Reduced downtime, rework, and unnecessary material consumption.",
        "Снижение простоев, переделок и лишнего расхода материалов.",
        "Mazāk dīkstāves, pārstrādes un lieka materiālu patēriņa.",
    ),
    (
        "solutions",
        "section_processOptimization",
        "expectedResults_4",
        "Clear recommendations for production and technologists.",
        "Понятные рекомендации для производства и технолога.",
        "Skaidri ieteikumi ražošanai un tehnologam.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "title",
        "Shielding gas selection",
        "Подбор защитных газов",
        "Aizsarggāzu izvēle",
    ),
    (
        "solutions",
        "section_gasSelection",
        "problems_1",
        "Weld quality is unstable with the current gas mix.",
        "Качество шва нестабильно при текущей газовой смеси.",
        "Šuves kvalitāte ar pašreizējo gāzu maisījumu ir nestabila.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "problems_2",
        "Porosity, spatter, oxidation, or poor weld appearance occurs.",
        "Есть пористость, разбрызгивание, окисление или плохой внешний вид шва.",
        "Parādās porainība, šļakatas, oksidēšanās vai slikts šuves izskats.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "problems_3",
        "Gas consumption is high, but quality does not improve.",
        "Расход газа высокий, но качество не улучшается.",
        "Gāzes patēriņš ir augsts, bet kvalitāte neuzlabojas.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "problems_4",
        "The gas is selected by habit, not by material and process.",
        "Газ выбран по привычке, а не под материал и процесс.",
        "Gāze izvēlēta pēc ieraduma, nevis pēc materiāla un procesa.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "causes_1",
        "Gas mixture, flow, nozzle, or electrode stickout does not match the material and shielding conditions.",
        "Газовая смесь, расход, сопло или вылет электрода не соответствуют материалу и условиям защиты.",
        "Gāzu maisījums, plūsma, sprausla vai elektroda izvirzījums neatbilst materiālam un aizsardzības apstākļiem.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "causes_2",
        "Drafts, joint access, welding position, or equipment settings affect shielding.",
        "На защиту влияют сквозняки, доступ к шву, положение сварки или настройки оборудования.",
        "Aizsardzību ietekmē caurvējš, piekļuve šuvei, metināšanas pozīcija vai iekārtas iestatījumi.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "analysisItems_1",
        "Checking material, MIG/MAG or TIG process, thickness, welding position, and weld requirements.",
        "Проверка материала, процесса MIG/MAG или TIG, толщины, положения сварки и требований к шву.",
        "Materiāla, MIG/MAG vai TIG procesa, biezuma, metināšanas pozīcijas un šuves prasību pārbaude.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "analysisItems_2",
        "Reviewing the current gas mix, flow rate, nozzle, electrode stickout, and shielding conditions.",
        "Анализ текущей газовой смеси, расхода, сопла, вылета электрода и условий защиты.",
        "Esošā gāzu maisījuma, plūsmas, sprauslas, elektroda izvirzījuma un aizsardzības apstākļu analīze.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "analysisItems_3",
        "Comparing gas options by quality, speed, appearance, and cost.",
        "Сравнение вариантов газов с точки зрения качества, скорости, внешнего вида и затрат.",
        "Gāzu variantu salīdzināšana pēc kvalitātes, ātruma, izskata un izmaksām.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "analysisItems_4",
        "Checking the effect of drafts, joint access, and equipment settings.",
        "Проверка влияния сквозняков, доступа к шву и настроек оборудования.",
        "Caurvēja, piekļuves šuvei un iekārtas iestatījumu ietekmes pārbaude.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "solutionSteps_1",
        "Match weld requirements with possible gas mixtures and a flow range.",
        "Сопоставить требования к шву с возможными газовыми смесями и диапазоном расхода.",
        "Saskaņot šuves prasības ar iespējamajiem gāzu maisījumiem un plūsmas diapazonu.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "solutionSteps_2",
        "Verify the chosen option using real joint access and actual parameters.",
        "Проверить выбранный вариант на реальном доступе к шву и фактических режимах.",
        "Pārbaudīt izvēlēto variantu ar reālu piekļuvi šuvei un faktiskajiem režīmiem.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "expectedResults_1",
        "A justified shielding gas choice or gas mix range.",
        "Обоснованный выбор защитного газа или диапазона смесей.",
        "Pamatota aizsarggāzes vai gāzu maisījuma diapazona izvēle.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "expectedResults_2",
        "More stable weld pool shielding and weld quality.",
        "Стабильнее защита сварочной ванны и качество шва.",
        "Stabilāka metināšanas vannas aizsardzība un šuves kvalitāte.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "expectedResults_3",
        "Reduced unnecessary gas consumption where possible.",
        "Снижение лишнего расхода газа там, где это возможно.",
        "Lieka gāzes patēriņa samazināšana, kur tas ir iespējams.",
    ),
    (
        "solutions",
        "section_gasSelection",
        "expectedResults_4",
        "A clearer link between gas, parameters, and result.",
        "Более понятная связь между газом, режимами и результатом.",
        "Skaidrāka saikne starp gāzi, režīmiem un rezultātu.",
    ),
    (
        "solutions",
        "section_training",
        "title",
        "Personnel training",
        "Обучение персонала",
        "Personāla apmācība",
    ),
    (
        "solutions",
        "section_training",
        "problems_1",
        "New welders do not produce stable quality.",
        "Новые сварщики не дают стабильного качества.",
        "Jauni metinātāji nesasniedz stabilu kvalitāti.",
    ),
    (
        "solutions",
        "section_training",
        "problems_2",
        "Errors repeat because process causes are not explained.",
        "Ошибки повторяются, потому что причины процесса не объяснены.",
        "Kļūdas atkārtojas, jo procesa cēloņi nav izskaidroti.",
    ),
    (
        "solutions",
        "section_training",
        "problems_3",
        "Production depends on a few experienced employees.",
        "Производство зависит от нескольких опытных сотрудников.",
        "Ražošana ir atkarīga no dažiem pieredzējušiem darbiniekiem.",
    ),
    (
        "solutions",
        "section_training",
        "problems_4",
        "Technical requirements exist, but personnel apply them unevenly.",
        "Технологические требования есть, но персонал применяет их неравномерно.",
        "Tehnoloģiskās prasības ir, bet personāls tās pielieto nevienmērīgi.",
    ),
    (
        "solutions",
        "section_training",
        "causes_1",
        "People know separate techniques but not the link between settings, technique, and defects.",
        "Персонал знает отдельные приёмы, но не понимает связь режима, техники и дефекта.",
        "Personāls zina atsevišķus paņēmienus, bet ne saikni starp režīmu, tehniku un defektu.",
    ),
    (
        "solutions",
        "section_training",
        "causes_2",
        "Training is not tied to real parts, requirements, and common shop-floor mistakes.",
        "Обучение не привязано к реальным изделиям, требованиям и типовым ошибкам цеха.",
        "Apmācība nav piesaistīta reāliem izstrādājumiem, prasībām un tipiskām ceha kļūdām.",
    ),
    (
        "solutions",
        "section_training",
        "analysisItems_1",
        "Assessing current welder skill level and typical mistakes.",
        "Оценка текущего уровня сварщиков и типичных ошибок.",
        "Esošā metinātāju līmeņa un tipisko kļūdu novērtēšana.",
    ),
    (
        "solutions",
        "section_training",
        "analysisItems_2",
        "Checking understanding of parameters, part preparation, torch technique, and weld inspection.",
        "Проверка понимания режимов, подготовки деталей, техники ведения горелки и контроля шва.",
        "Režīmu, detaļu sagatavošanas, degļa vadīšanas tehnikas un šuves kontroles izpratnes pārbaude.",
    ),
    (
        "solutions",
        "section_training",
        "analysisItems_3",
        "Defining training topics for the specific process and production tasks.",
        "Определение тем обучения под конкретный процесс и задачи производства.",
        "Apmācību tēmu noteikšana konkrētajam procesam un ražošanas uzdevumiem.",
    ),
    (
        "solutions",
        "section_training",
        "analysisItems_4",
        "Connecting practical exercises with real defects and quality requirements.",
        "Связь практических упражнений с реальными дефектами и требованиями качества.",
        "Praktisko vingrinājumu sasaistīšana ar reāliem defektiem un kvalitātes prasībām.",
    ),
    (
        "solutions",
        "section_training",
        "solutionSteps_1",
        "Build training around the specific process, material, and common defects.",
        "Собрать программу обучения под конкретный процесс, материал и типовые дефекты.",
        "Izveidot apmācību konkrētam procesam, materiālam un tipiskajiem defektiem.",
    ),
    (
        "solutions",
        "section_training",
        "solutionSteps_2",
        "Practice with clear control and repeatability criteria.",
        "Отработать практику с понятными критериями контроля и повторяемости.",
        "Atstrādāt praksi ar skaidriem kontroles un atkārtojamības kritērijiem.",
    ),
    (
        "solutions",
        "section_training",
        "expectedResults_1",
        "A more consistent skill level across employees.",
        "Более единый уровень работы между сотрудниками.",
        "Vienmērīgāks darba līmenis starp darbiniekiem.",
    ),
    (
        "solutions",
        "section_training",
        "expectedResults_2",
        "Fewer recurring mistakes and defects.",
        "Меньше повторяющихся ошибок и дефектов.",
        "Mazāk atkārtotu kļūdu un defektu.",
    ),
    (
        "solutions",
        "section_training",
        "expectedResults_3",
        "Practical skills tied to real products and processes.",
        "Практические навыки, привязанные к реальным изделиям и процессам.",
        "Praktiskas prasmes, kas saistītas ar reāliem izstrādājumiem un procesiem.",
    ),
    (
        "solutions",
        "section_training",
        "expectedResults_4",
        "Understanding not only how to weld, but why defects appear.",
        "Понимание не только как варить, но и почему возникают дефекты.",
        "Izpratne ne tikai par to, kā metināt, bet arī kāpēc rodas defekti.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "title",
        "Project support / WPS implementation",
        "Поддержка проектов / внедрение WPS",
        "Projektu atbalsts / WPS ieviešana",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "problems_1",
        "The process needs a stable launch, but parameters are not documented yet.",
        "Процесс нужно запустить стабильно, но параметры еще не оформлены.",
        "Process jāpalaiž stabili, bet parametri vēl nav noformēti.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "problems_2",
        "WPS or pWPS exists formally, but production does not apply it consistently.",
        "WPS или pWPS есть формально, но производство не работает по ним одинаково.",
        "WPS vai pWPS ir formāli, bet ražošana pēc tiem nestrādā vienādi.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "problems_3",
        "Customer requirements, audits, or projects require traceability.",
        "Требования заказчика, аудит или проект требуют прослеживаемости.",
        "Klienta prasības, audits vai projekts prasa izsekojamību.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "problems_4",
        "Documentation, real parameters, and quality are not connected well enough.",
        "Не хватает связи между документацией, реальными режимами и качеством.",
        "Trūkst saiknes starp dokumentāciju, reālajiem režīmiem un kvalitāti.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "causes_1",
        "Documentation does not reflect actual equipment, joint, and workplace constraints.",
        "Документация не отражает фактические ограничения оборудования, соединений и рабочих мест.",
        "Dokumentācija neatspoguļo faktiskos iekārtu, savienojumu un darba vietu ierobežojumus.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "causes_2",
        "Parameters have not been checked under the conditions where production will make real parts.",
        "Параметры не проверены в условиях, где производство будет выполнять реальные изделия.",
        "Parametri nav pārbaudīti apstākļos, kuros ražošana izpildīs reālus izstrādājumus.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "analysisItems_1",
        "Checking project requirements, material, joints, equipment, and available processes.",
        "Проверка требований проекта, материала, соединений, оборудования и доступных процессов.",
        "Projekta prasību, materiāla, savienojumu, iekārtu un pieejamo procesu pārbaude.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "analysisItems_2",
        "Reviewing existing WPS/pWPS, process sheets, and actual parameters.",
        "Анализ существующих WPS/pWPS, технологических карт и фактических режимов.",
        "Esošo WPS/pWPS, tehnoloģisko karšu un faktisko režīmu analīze.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "analysisItems_3",
        "Comparing documentation with what happens at the workplace.",
        "Сопоставление документации с тем, что реально происходит на рабочем месте.",
        "Dokumentācijas salīdzināšana ar to, kas reāli notiek darba vietā.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "analysisItems_4",
        "Defining which parameters should be fixed, checked, or validated on samples.",
        "Определение, какие параметры нужно зафиксировать, проверить или уточнить на образцах.",
        "Parametru noteikšana, kurus vajag fiksēt, pārbaudīt vai precizēt uz paraugiem.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "solutionSteps_1",
        "Align WPS/pWPS with actual parameters, control points, and welder actions.",
        "Согласовать WPS/pWPS с фактическими режимами, контролем и действиями сварщиков.",
        "Saskaņot WPS/pWPS ar faktiskajiem režīmiem, kontroli un metinātāju darbībām.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "solutionSteps_2",
        "Fix the parameters needed for launch, control, and traceability.",
        "Зафиксировать параметры, которые нужны для запуска, контроля и прослеживаемости.",
        "Fiksēt parametrus, kas vajadzīgi palaišanai, kontrolei un izsekojamībai.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "expectedResults_1",
        "A clearer WPS implementation in real production.",
        "Более понятное внедрение WPS в реальное производство.",
        "Skaidrāka WPS ieviešana reālā ražošanā.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "expectedResults_2",
        "Aligned parameters and actions for welders, supervisors, and technologists.",
        "Согласованные параметры и действия для сварщиков, мастеров и технологов.",
        "Saskaņoti parametri un darbības metinātājiem, meistariem un tehnologiem.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "expectedResults_3",
        "Fewer gaps between documentation and practice.",
        "Меньше расхождений между документацией и практикой.",
        "Mazāk atšķirību starp dokumentāciju un praksi.",
    ),
    (
        "solutions",
        "section_wpsSupport",
        "expectedResults_4",
        "Readiness for internal control, customer requirements, or audits.",
        "Готовность к внутреннему контролю, требованиям заказчика или аудиту.",
        "Gatavība iekšējai kontrolei, klienta prasībām vai auditam.",
    ),
    (
        "expertise",
        "hero",
        "expertiseDecisionEyebrow",
        "Decision Layer",
        "Слой решений",
        "Risinājumu slānis",
    ),
    ("expertise", "hero", "competenciesTitle", "Expertise", "Экспертиза", "Ekspertīze"),
    (
        "expertise",
        "hero",
        "expertisePageIntro",
        "Technical areas I work with: welding processes, shielding gases, metallurgy, cutting gases, WPS, and safe gas handling.",
        "Технические области, с которыми я работаю: сварочные процессы, защитные газы, металлургия, газы для резки, WPS и безопасная работа с газами.",
        "Tehniskās jomas, ar kurām strādāju: metināšanas procesi, aizsarggāzes, metalurģija, gāzes griešanai, WPS un drošs darbs ar gāzēm.",
    ),
    ("expertise", "competency_mig_mag", "group", "Processes", "Процессы", "Procesi"),
    (
        "expertise",
        "competency_mig_mag",
        "title",
        "MIG/MAG welding",
        "MIG/MAG сварка",
        "MIG/MAG metināšana",
    ),
    (
        "expertise",
        "competency_mig_mag",
        "description",
        "WPS, parameter windows, process control, and practical welding documentation.",
        "WPS, окна параметров, контроль процесса и практическая сварочная документация.",
        "WPS, parametru logi, procesa kontrole un praktiska metināšanas dokumentācija.",
    ),
    ("expertise", "competency_tig", "group", "Processes", "Процессы", "Procesi"),
    (
        "expertise",
        "competency_tig",
        "title",
        "TIG aluminum / stainless steel welding",
        "TIG сварка алюминия / нержавеющей стали",
        "TIG metināšana alumīnijam / nerūsējošajam tēraudam",
    ),
    (
        "expertise",
        "competency_tig",
        "description",
        "AC/DC TIG setup, heat control, torch technique, and filler rhythm.",
        "Настройка AC/DC TIG, контроль тепла, техника горелки и подача присадки.",
        "AC/DC TIG iestatīšana, siltuma kontrole, degļa tehnika un piedevas ritms.",
    ),
    ("expertise", "competency_gases", "group", "Gases", "Газы", "Gāzes"),
    (
        "expertise",
        "competency_gases",
        "title",
        "Shielding gases for MIG/MAG/TIG",
        "Защитные газы для MIG/MAG/TIG",
        "Aizsarggāzes MIG/MAG/TIG",
    ),
    (
        "expertise",
        "competency_gases",
        "description",
        "Gas mixtures, flow rate, shielding conditions, and consumption checks.",
        "Газовые смеси, расход, условия защиты и проверка потребления.",
        "Gāzu maisījumi, plūsma, aizsardzības apstākļi un patēriņa pārbaude.",
    ),
    (
        "expertise",
        "competency_metallurgy",
        "group",
        "Metallurgy",
        "Металлургия",
        "Metalurģija",
    ),
    (
        "expertise",
        "competency_metallurgy",
        "title",
        "Welding metallurgy",
        "Металлургия сварки",
        "Metināšanas metalurģija",
    ),
    (
        "expertise",
        "competency_metallurgy",
        "description",
        "Base materials, heat input, microstructure, and weld behaviour.",
        "Материалы, тепловложение, микроструктура и поведение сварного соединения.",
        "Materiāli, siltuma ievade, mikrostruktūra un metinātā savienojuma uzvedība.",
    ),
    ("expertise", "competency_quality", "group", "Materials", "Материалы", "Materiāli"),
    (
        "expertise",
        "competency_quality",
        "title",
        "Cutting gases",
        "Газы для резки",
        "Gāzes griešanai",
    ),
    (
        "expertise",
        "competency_quality",
        "description",
        "Fuel gas choice, oxygen cutting setup, and parameter estimation.",
        "Выбор горючего газа, настройка кислородной резки и оценка параметров.",
        "Deggāzes izvēle, skābekļa griešanas iestatījumi un parametru novērtējums.",
    ),
    ("expertise", "competency_safety", "group", "Safety", "Безопасность", "Drošība"),
    (
        "expertise",
        "competency_safety",
        "title",
        "Gas safety",
        "Техника безопасности с газами",
        "Drošība ar gāzēm",
    ),
    (
        "expertise",
        "competency_safety",
        "description",
        "Cylinder handling, workplace practice, and safe gas use.",
        "Работа с баллонами, организация рабочего места и безопасное применение газов.",
        "Balonu apstrāde, darba vietas prakse un droša gāzu lietošana.",
    ),
    (
        "expertise",
        "cta_solutions",
        "expertiseSolutionsCtaTitle",
        "See how this capability is applied",
        "Посмотреть, как компетенция применяется",
        "Skatīt, kā kompetence tiek pielietota",
    ),
    (
        "expertise",
        "cta_solutions",
        "expertiseSolutionsCtaText",
        "Open solution patterns to connect these competencies with typical welding problems.",
        "Откройте паттерны решений, чтобы связать компетенции с типовыми сварочными задачами.",
        "Atveriet risinājumu modeļus, lai sasaistītu kompetences ar tipiskiem metināšanas uzdevumiem.",
    ),
    (
        "expertise",
        "cta_solutions",
        "expertiseSolutionsCta",
        "Go to Solutions",
        "Перейти к решениям",
        "Uz risinājumiem",
    ),
    (
        "expertise",
        "cta_experience",
        "expertiseExperienceCtaTitle",
        "See real-world validation",
        "Посмотреть подтверждение на практике",
        "Skatīt praktisko pierādījumu",
    ),
    (
        "expertise",
        "cta_experience",
        "expertiseExperienceCtaText",
        "Open experience to see roles, contexts, actions, and observed outcomes.",
        "Откройте опыт: роли, контексты, действия и наблюдаемые результаты.",
        "Atveriet pieredzi: lomas, konteksti, darbības un novērotie rezultāti.",
    ),
    (
        "expertise",
        "cta_experience",
        "expertiseExperienceCta",
        "Go to Experience",
        "Перейти к опыту",
        "Uz pieredzi",
    ),
]


def seed_site_text_blocks(apps, schema_editor):
    SiteTextBlock = apps.get_model("pages", "SiteTextBlock")

    for page, block, key, text_en, text_ru, text_lv in TEXT_BLOCKS:
        SiteTextBlock.objects.update_or_create(
            page=page,
            block=block,
            key=key,
            defaults={
                "text_en": text_en,
                "text_ru": text_ru,
                "text_lv": text_lv,
            },
        )


def remove_site_text_blocks(apps, schema_editor):
    SiteTextBlock = apps.get_model("pages", "SiteTextBlock")
    keys_by_page_block = {}
    for page, block, key, *_ in TEXT_BLOCKS:
        keys_by_page_block.setdefault((page, block), []).append(key)

    for (page, block), keys in keys_by_page_block.items():
        SiteTextBlock.objects.filter(page=page, block=block, key__in=keys).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0019_contact_site_text_blocks"),
    ]

    operations = [
        migrations.RunPython(seed_site_text_blocks, remove_site_text_blocks),
    ]
