# Generated by Django 4.2.30 on 2026-08-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0048_book_page_image_alt_i18n"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolutionSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_key", models.SlugField(unique=True)),
                ("title_en", models.CharField(blank=True, max_length=500)),
                ("title_ru", models.CharField(blank=True, max_length=500)),
                ("title_lv", models.CharField(blank=True, max_length=500)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Solutions – секция",
                "verbose_name_plural": "Solutions – секции",
                "db_table": "pages_solution_section",
                "ordering": ["order", "item_key"],
            },
        ),
        migrations.CreateModel(
            name="SolutionColumnGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "column",
                    models.CharField(
                        choices=[
                            ("problem", "Проблема"),
                            ("cause", "Причина"),
                            ("analysis", "Инженерный анализ"),
                            ("solution", "Решение"),
                            ("result", "Результат"),
                        ],
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_groups",
                        to="pages.solutionsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solutions – колонка",
                "verbose_name_plural": "Solutions – колонки",
                "db_table": "pages_solution_column_group",
                "ordering": ["section__order", "column"],
            },
        ),
        migrations.CreateModel(
            name="SolutionBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("text_en", models.TextField(blank=True)),
                ("text_ru", models.TextField(blank=True)),
                ("text_lv", models.TextField(blank=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullets",
                        to="pages.solutioncolumngroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solutions – абзац",
                "verbose_name_plural": "Solutions – абзацы",
                "db_table": "pages_solution_bullet",
                "ordering": ["group", "order"],
            },
        ),
        migrations.AddConstraint(
            model_name="solutioncolumngroup",
            constraint=models.UniqueConstraint(
                fields=("section", "column"), name="unique_solution_section_column"
            ),
        ),
        migrations.AddConstraint(
            model_name="solutionbullet",
            constraint=models.UniqueConstraint(
                fields=("group", "order"), name="unique_solution_bullet_order"
            ),
        ),
    ]
