# Generated by Django 5.2.12 on 2026-07-20 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0005_multilingual_entities"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "locale",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ru", "Русский"),
                            ("lv", "Latviešu"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("defects", "Defects"),
                            ("process", "Process"),
                            ("training", "Training"),
                            ("cooperation", "Cooperation"),
                            ("commercial", "Commercial"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("replied", "Replied"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("answered", models.BooleanField(default=False)),
                ("answer_text", models.TextField(blank=True)),
                ("source_page", models.CharField(blank=True, max_length=255)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact inquiry",
                "verbose_name_plural": "Contact inquiries",
                "db_table": "leads_contact_inquiries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="leads_conta_status_eca8a7_idx",
                    ),
                    models.Index(fields=["email"], name="leads_conta_email_1a05f6_idx"),
                    models.Index(
                        fields=["request_type"], name="leads_conta_request_ce4b78_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeadEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("subscribe", "Subscribe"),
                            ("question_sent", "Question sent"),
                            ("inquiry_sent", "Inquiry sent"),
                            ("doi_confirmed", "DOI confirmed"),
                            ("unsubscribe", "Unsubscribe"),
                        ],
                        max_length=32,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "locale",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en", "English"),
                            ("ru", "Русский"),
                            ("lv", "Latviešu"),
                        ],
                        max_length=5,
                    ),
                ),
                ("page_path", models.CharField(blank=True, max_length=512)),
                ("article_slug", models.SlugField(blank=True, max_length=255)),
                ("referrer", models.CharField(blank=True, max_length=512)),
                ("utm_source", models.CharField(blank=True, max_length=255)),
                ("utm_medium", models.CharField(blank=True, max_length=255)),
                ("utm_campaign", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lead event",
                "verbose_name_plural": "Lead events",
                "db_table": "leads_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="leads_event_event_t_031d40_idx",
                    ),
                    models.Index(fields=["email"], name="leads_event_email_a17e47_idx"),
                    models.Index(
                        fields=["article_slug"], name="leads_event_article_b2810a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubscriberReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ru", "Русский"),
                            ("lv", "Latviešu"),
                        ],
                        max_length=5,
                    ),
                ),
                ("newsletter", models.BooleanField(default=True)),
                ("brevo_contact_id", models.CharField(blank=True, max_length=64)),
                ("brevo_list_id", models.CharField(blank=True, max_length=64)),
                ("doi_confirmed", models.BooleanField(default=False)),
                (
                    "first_source",
                    models.CharField(
                        choices=[
                            ("blog_subscribe", "Blog subscribe"),
                            ("article_question", "Article question"),
                            ("contact", "Contact"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("first_article_slug", models.SlugField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscriber reference",
                "verbose_name_plural": "Subscriber references",
                "db_table": "leads_subscriber_references",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["newsletter", "doi_confirmed"],
                        name="leads_subsc_newslet_1972e5_idx",
                    ),
                    models.Index(
                        fields=["first_source"], name="leads_subsc_first_s_f6feb5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ArticleQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "locale",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ru", "Русский"),
                            ("lv", "Latviešu"),
                        ],
                        max_length=5,
                    ),
                ),
                ("article_slug", models.SlugField(blank=True, max_length=255)),
                ("article_title", models.CharField(blank=True, max_length=255)),
                ("question", models.TextField()),
                ("subscribe_opt_in", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In progress"),
                            ("answered", "Answered"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("answered", models.BooleanField(default=False)),
                ("answer_text", models.TextField(blank=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("brevo_synced", models.BooleanField(default=False)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_questions",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article question",
                "verbose_name_plural": "Article questions",
                "db_table": "leads_article_questions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="leads_artic_status_9bc6e6_idx",
                    ),
                    models.Index(fields=["email"], name="leads_artic_email_f9d3fd_idx"),
                    models.Index(
                        fields=["article_slug"], name="leads_artic_article_37724d_idx"
                    ),
                ],
            },
        ),
    ]
